version: '3.8'

services:
  web:
    build: app
    restart: always
    command: daphne -u /tmp/daphne.sock hello_django.asgi:application
    volumes:
      - ./app/:/root/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: mariadb:10.8.2-rc-focal
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb/data/
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_USER=hello_django
      - MARIADB_PASSWORD=hello_django
      - MARIADB_DATABASE=hello_django_dev

volumes:
  mariadb_data:
