version: '3.8'

services:
  web:
    build:
      context: app
      dockerfile: app/Dockerfile.prod
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 hello_django.asgi:application
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    # The port 8000 is only exposed internally, to other Docker services.
    expose:
        - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  nginx:
    build: nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "8000:80"
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: