# roles/webservers/tasks/main.yml
- name: Install the correct web server for RHEL
  import_tasks: centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
